[workspace]
members = ["crates/linrdp-proto", "crates/linrdp"]
resolver = "3"
exclude = ["vendor/minifb"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/Danubii/linrdp"

[workspace.lints.rust]
unsafe_code = "forbid"

[patch.crates-io]
minifb = { path = "vendor/minifb" }
