[workspace]
members = ["crates/linrdp-proto", "crates/fjern"]
resolver = "3"
exclude = ["vendor/minifb", "vendor/vnc-rs"]

[workspace.package]
version = "0.2.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/zeq0r/fjern"

[workspace.lints.rust]
unsafe_code = "forbid"

[patch.crates-io]
minifb = { path = "vendor/minifb" }
vnc-rs = { path = "vendor/vnc-rs" }
