[package]
name = "linrdp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A simple Linux RDP client (early development)"
publish = false

[dependencies]
linrdp-proto = { path = "../linrdp-proto" }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-native-certs = "0.8"
x509-cert = { version = "0.2", default-features = false, features = ["std"] }

[dev-dependencies]
rcgen = "0.14"

[lints]
workspace = true
