[package]
name = "linrdp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "An Omarchy-first Linux client for RDP and VNC (early development)"
publish = false

[dependencies]
linrdp-proto = { path = "../linrdp-proto" }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-native-certs = "0.8"
ring = "0.17"
x509-cert = { version = "0.2", default-features = false, features = ["std"] }
sspi = { version = "0.21.3", default-features = false, features = ["ring"] }
zeroize = "1"
rpassword = "7"
der = { version = "0.7.10", features = ["derive", "std"] }
minifb = "0.28"
raw-window-handle = "0.6.2"
wl-clipboard-rs = "0.9.3"
tempfile = "3"
url = "2"
libc = "0.2"
cap-std = "4.0.3"
rustix = { version = "1", features = ["fs"] }
crossterm = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
unicode-width = "0.2"
vnc-rs = "0.5.3"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "net", "time", "io-util", "sync"] }
openssl = "0.10.81"
tokio-openssl = "0.6.5"

[dev-dependencies]
rcgen = "0.14"

[lints]
workspace = true
