use linrdp_proto::credssp::{Error, MAX_MESSAGE_SIZE, MAX_TOKENS, TsRequest, frame_length};

// Independently assembled from the ASN.1 schema, not generated by the encoder.
const VERSION_ONLY: &[u8] = &[0x30, 5, 0xa0, 3, 2, 1, 6];
const TOKEN: &[u8] = &[
    0x30, 0x12, 0xa0, 3, 2, 1, 6, 0xa1, 0x0b, 0x30, 9, 0x30, 7, 0xa0, 5, 4, 3, b'a', b'b', b'c',
];
const LOGON_FAILURE: &[u8] = &[
    0x30, 0x0e, 0xa0, 3, 2, 1, 6, 0xa4, 7, 2, 5, 0, 0xc0, 0, 0, 0x6d,
];

#[test]
fn matches_independent_version_and_token_vectors() {
    assert_eq!(TsRequest::new().encode().unwrap(), VERSION_ONLY);
    let mut request = TsRequest::new();
    request.nego_tokens.push(b"abc");
    assert_eq!(request.encode().unwrap(), TOKEN);
    assert_eq!(TsRequest::decode(TOKEN).unwrap(), request);
}

#[test]
fn preserves_unsigned_ntstatus_and_stops_on_any_error_field() {
    let request = TsRequest::decode(LOGON_FAILURE).unwrap();
    assert_eq!(request.error_code, Some(0xc000006d));
    assert_eq!(request.encode().unwrap(), LOGON_FAILURE);
    assert!(matches!(
        request.check_server_status(),
        Err(Error::ServerStatus(0xc000006d))
    ));
    let mut zero = TsRequest::new();
    zero.error_code = Some(0);
    assert!(matches!(
        zero.check_server_status(),
        Err(Error::ServerStatus(0))
    ));
}

#[test]
fn round_trips_opaque_fields_and_long_lengths() {
    let bytes = vec![0x42; 4096];
    let nonce = [0x24; 32];
    let mut request = TsRequest::new();
    request.nego_tokens = vec![b"first", &bytes];
    request.auth_info = Some(b"sealed credentials");
    request.pub_key_auth = Some(b"sealed binding");
    request.client_nonce = Some(&nonce);
    let encoded = request.encode().unwrap();
    assert_eq!(frame_length(&encoded).unwrap(), Some(encoded.len()));
    assert_eq!(TsRequest::decode(&encoded).unwrap(), request);
}

#[test]
fn rejects_all_truncations_and_trailing_data() {
    for packet in [TOKEN, LOGON_FAILURE] {
        for length in 0..packet.len() {
            assert!(TsRequest::decode(&packet[..length]).is_err());
        }
        let mut extra = packet.to_vec();
        extra.push(0);
        assert!(TsRequest::decode(&extra).is_err());
    }
}

#[test]
fn rejects_duplicate_unordered_unknown_and_missing_fields() {
    for packet in [
        vec![0x30, 0],
        vec![0x30, 10, 0xa0, 3, 2, 1, 6, 0xa0, 3, 2, 1, 6],
        vec![0x30, 10, 0xa4, 3, 2, 1, 0, 0xa0, 3, 2, 1, 6],
        vec![0x30, 10, 0xa0, 3, 2, 1, 6, 0xa6, 3, 2, 1, 0],
        vec![0x30, 5, 0x80, 3, 2, 1, 6],
    ] {
        assert!(TsRequest::decode(&packet).is_err(), "{packet:x?}");
    }
}

#[test]
fn rejects_negative_nonminimal_and_overflowing_integers() {
    for value in [vec![0xff], vec![0, 6], vec![1, 0, 0, 0, 0]] {
        let mut packet = vec![
            0x30,
            (value.len() + 4) as u8,
            0xa0,
            (value.len() + 2) as u8,
            2,
            value.len() as u8,
        ];
        packet.extend(value);
        assert!(TsRequest::decode(&packet).is_err());
    }
}

#[test]
fn enforces_nonce_size_and_version_policy() {
    for length in [0usize, 31, 33] {
        let mut packet = vec![
            0x30,
            (9 + length) as u8,
            0xa0,
            3,
            2,
            1,
            6,
            0xa5,
            (2 + length) as u8,
            4,
            length as u8,
        ];
        packet.resize(11 + length, 0);
        assert!(TsRequest::decode(&packet).is_err());
    }
    for version in [2, 3, 4, 5, 6, 7, u32::MAX] {
        let mut request = TsRequest::new();
        request.version = version;
        let encoded = request.encode().unwrap();
        let decoded = TsRequest::decode(&encoded).unwrap();
        if version < 5 {
            assert!(matches!(
                decoded.check_server_status(),
                Err(Error::UnsupportedVersion(_))
            ));
            request.client_nonce = Some(&[0; 32]);
            assert!(request.encode().is_err());
        } else {
            assert_eq!(decoded.check_server_status().unwrap(), version.min(6));
        }
    }
}

#[test]
fn bounds_message_size_and_token_count_on_both_paths() {
    let oversized = vec![0; MAX_MESSAGE_SIZE + 1];
    assert!(matches!(
        TsRequest::decode(&oversized),
        Err(Error::TooLarge)
    ));
    let mut request = TsRequest::new();
    request.auth_info = Some(&oversized);
    assert!(matches!(request.encode(), Err(Error::TooLarge)));
    request.auth_info = None;
    request.nego_tokens = vec![b""; MAX_TOKENS + 1];
    assert!(request.encode().is_err());
    // 17 zero-length OCTET STRING tokens wrapped in NegoData.
    let mut packet = vec![0x30, 111, 0xa0, 3, 2, 1, 6, 0xa1, 104, 0x30, 102];
    for _ in 0..17 {
        packet.extend([0x30, 4, 0xa0, 2, 4, 0]);
    }
    assert!(TsRequest::decode(&packet).is_err());
}

#[test]
fn frame_header_supports_fragmentation_and_rejects_invalid_lengths() {
    for prefix in [&[][..], &[0x30], &[0x30, 0x82], &[0x30, 0x82, 1]] {
        assert_eq!(frame_length(prefix).unwrap(), None);
    }
    assert_eq!(frame_length(&[0x30, 0x82, 1, 0]).unwrap(), Some(260));
    assert_eq!(frame_length(VERSION_ONLY).unwrap(), Some(7));
    for prefix in [
        vec![0x31],
        vec![0x30, 0x80],
        vec![0x30, 0x81, 0x7f],
        vec![0x30, 0x82, 0, 0x80],
        vec![0x30, 0x84],
        vec![0x30, 0x83, 0x10, 0, 0],
    ] {
        assert!(frame_length(&prefix).is_err());
    }
}

#[test]
fn debug_output_does_not_expose_authentication_payloads() {
    let mut request = TsRequest::new();
    request.nego_tokens.push(b"secret-token");
    request.auth_info = Some(b"secret-credentials");
    request.pub_key_auth = Some(b"secret-binding");
    assert_eq!(
        format!("{request:?}"),
        "TsRequest { version: 6, token_count: 1, has_auth_info: true, has_pub_key_auth: true, error_code: None, has_client_nonce: false }"
    );
}

#[test]
fn accepts_signed_ntstatus_without_losing_failure_bits() {
    let bytes = [
        0x30, 0x0d, 0xa0, 3, 2, 1, 6, 0xa4, 6, 2, 4, 0xc0, 0, 0, 0x6d,
    ];
    let request = TsRequest::decode(&bytes).unwrap();
    assert_eq!(request.error_code, Some(0xc000006d));
    assert!(matches!(
        request.check_server_status(),
        Err(Error::ServerStatus(0xc000006d))
    ));
    assert_eq!(request.encode().unwrap(), LOGON_FAILURE);
}

#[test]
fn rejects_status_integers_outside_signed_or_unsigned_32_bits() {
    for value in [[1, 0, 0, 0, 0], [0xff, 0x7f, 0xff, 0xff, 0xff]] {
        let mut bytes = vec![0x30, 0x0e, 0xa0, 3, 2, 1, 6, 0xa4, 7, 2, 5];
        bytes.extend_from_slice(&value);
        assert!(TsRequest::decode(&bytes).is_err());
    }
}
